# base experiment, no rebalancing
# model with 8 conv layers
# L2 + Dropout regularization
# no data augmentation
experiment:
  data:
    channels: ['EEG_PR']
    balanced_training: False

  training:
    optimizer:
      class: 'Adam'
      l2_weight_decay: 1.e-4

  model:
    filters: 96
    classifier_dropout: [0.2, 0.2]
    feature_extr_dropout: [0.0, 0.2, 0.0, 0.2, 0.0, 0.2, 0.0, 0.2]
    name: 'model_8conv_2fc'
